eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone : http://58.149.234.98:5003/eureka
  server:
    registry-sync-retry-wait-ms: 5

#Setting logging levels
logging:
  file:
    path: /usr/local/pbeureka/logs
