eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone : http://58.149.234.98:5003
  server:
    wait-time-in-ms-when-sync-empty: 5

#Setting logging levels
logging:
  file:
    path: /usr/local/pbeureka/logs
