server:
  port: 5003

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone : http://localhost:5003/eureka
  server:
    registry-sync-retry-wait-ms: 5

spring:
  application:
    name: pbeureka

#Setting logging levels
#logging:
#  file:
#    path: /usr/local/pbeureka/logs
